{
 "title": "FastAPI Monitoring",
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate (req/s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "req/s" }
   ]
  },
  {
   "title": "Response Time (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(request_duration_seconds_bucket[1m]))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, rate(request_duration_seconds_bucket[1m]))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "CPU %" }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "targets": [
    { "expr": "memory_usage_percent", "legendFormat": "Memory %" }
   ]
  }
 ]
}