"""column changes

Revision ID: a5566bfc3dbb
Revises: 3c960ed656ef
Create Date: 2024-05-28 23:27:42.797689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a5566bfc3dbb'
down_revision: Union[str, None] = '3c960ed656ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
