name: FastAPI Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t '${{ secrets.DOCKER_USERNAME }}'/fastapi-docker:'${{ github.sha }}' -f xpense_tracker/Dockerfile .

      - name: Logging into Docker Hub
        run: docker login --username '${{ secrets.DOCKER_USERNAME }}' --password '${{ secrets.DOCKER_PASSWORD }}'

      - name: Push the image to docker hub
        run: docker push '${{ secrets.DOCKER_USERNAME }}'/fastapi-docker:'${{ github.sha }}'
